### YamlMime:ManagedReference
items:
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  commentId: T:GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  id: CompressionSettings
  parent: GlitchedPolygons.Services.CompressionUtility
  children:
  - GlitchedPolygons.Services.CompressionUtility.CompressionSettings.bufferSize
  - GlitchedPolygons.Services.CompressionUtility.CompressionSettings.compressionLevel
  - GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
  langs:
  - csharp
  - vb
  name: CompressionSettings
  nameWithType: CompressionSettings
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  type: Struct
  source:
    remote:
      path: src/CompressionSettings.cs
      branch: master
      repo: git@github.com:GlitchedPolygons/CompressionUtility.git
    id: CompressionSettings
    path: ../../src/CompressionSettings.cs
    startLine: 7
  assemblies:
  - GlitchedPolygons.Services.CompressionUtility
  namespace: GlitchedPolygons.Services.CompressionUtility
  summary: "\nThe compression relevant settings (such as buffer size, compression level, etc...).\n"
  example: []
  syntax:
    content: public struct CompressionSettings
    content.vb: Public Structure CompressionSettings
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.bufferSize
  commentId: F:GlitchedPolygons.Services.CompressionUtility.CompressionSettings.bufferSize
  id: bufferSize
  parent: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  langs:
  - csharp
  - vb
  name: bufferSize
  nameWithType: CompressionSettings.bufferSize
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.bufferSize
  type: Field
  source:
    remote:
      path: src/CompressionSettings.cs
      branch: master
      repo: git@github.com:GlitchedPolygons/CompressionUtility.git
    id: bufferSize
    path: ../../src/CompressionSettings.cs
    startLine: 12
  assemblies:
  - GlitchedPolygons.Services.CompressionUtility
  namespace: GlitchedPolygons.Services.CompressionUtility
  summary: "\nThe size of the underlying stream buffer. A reasonable value could be <code>65536</code><p> </p>\n"
  example: []
  syntax:
    content: public int bufferSize
    return:
      type: System.Int32
    content.vb: Public bufferSize As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.compressionLevel
  commentId: F:GlitchedPolygons.Services.CompressionUtility.CompressionSettings.compressionLevel
  id: compressionLevel
  parent: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  langs:
  - csharp
  - vb
  name: compressionLevel
  nameWithType: CompressionSettings.compressionLevel
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.compressionLevel
  type: Field
  source:
    remote:
      path: src/CompressionSettings.cs
      branch: master
      repo: git@github.com:GlitchedPolygons/CompressionUtility.git
    id: compressionLevel
    path: ../../src/CompressionSettings.cs
    startLine: 18
  assemblies:
  - GlitchedPolygons.Services.CompressionUtility
  namespace: GlitchedPolygons.Services.CompressionUtility
  summary: "\nChoose the desired compression level.<p> </p>\nThe default value favors speed over maximum efficiency (<see cref=\"!:System.IO.Compression.CompressionLevel.Fastest\"></see>).\n"
  example: []
  syntax:
    content: public CompressionLevel compressionLevel
    return:
      type: CompressionLevel
    content.vb: Public compressionLevel As CompressionLevel
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
  commentId: P:GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
  id: Default
  parent: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: CompressionSettings.Default
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
  type: Property
  source:
    remote:
      path: src/CompressionSettings.cs
      branch: master
      repo: git@github.com:GlitchedPolygons/CompressionUtility.git
    id: Default
    path: ../../src/CompressionSettings.cs
    startLine: 23
  assemblies:
  - GlitchedPolygons.Services.CompressionUtility
  namespace: GlitchedPolygons.Services.CompressionUtility
  summary: "\nGeneral-purpose default settings for compressing and decompressing all kinds of data. When unsure, use this!\n"
  example: []
  syntax:
    content: public static CompressionSettings Default { get; }
    parameters: []
    return:
      type: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
    content.vb: Public Shared ReadOnly Property Default As CompressionSettings
  overload: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: GlitchedPolygons.Services.CompressionUtility
  commentId: N:GlitchedPolygons.Services.CompressionUtility
  name: GlitchedPolygons.Services.CompressionUtility
  nameWithType: GlitchedPolygons.Services.CompressionUtility
  fullName: GlitchedPolygons.Services.CompressionUtility
- uid: System.Int32
  commentId: '!:System.Int32'
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CompressionLevel
  commentId: '!:CompressionLevel'
  isExternal: true
  name: CompressionLevel
  nameWithType: CompressionLevel
  fullName: CompressionLevel
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default*
  commentId: Overload:GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
  name: Default
  nameWithType: CompressionSettings.Default
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings.Default
- uid: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  commentId: T:GlitchedPolygons.Services.CompressionUtility.CompressionSettings
  parent: GlitchedPolygons.Services.CompressionUtility
  name: CompressionSettings
  nameWithType: CompressionSettings
  fullName: GlitchedPolygons.Services.CompressionUtility.CompressionSettings
