version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: dotnet restore
          command: dotnet restore
      - run:
          name: Run xunit tests
          command: dotnet test UnitTests/UnitTests.csproj