version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore
      - run:
          name: Run xunit tests
          command: dotnet test CompressionUtility.Tests/CompressionUtility.Tests.csproj