version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore
      - run:
          name: Run xunit tests
          command: cd tests && dotnet test